[project]
name = "instaget"
version = "0.1.0"
description = "Gets from Insta"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ['instaloader@git+https://github.com/danudey/instaloader.git@master', 'psutil']

[project.scripts]
instaget = "instaget.main:main"